### ISSUE TITLE
Need a way to get score

### ISSUE THREAD

**Issue by hongjiehuang** [RyanLinrm/CSC473Project#124]
We need to create functions to let player collect scores by killling enemies or destorying enemy towers so that we can later connect it to the leaderboard.

**Comment by RyanLinrm** [comment]
I've finished the getting score from killing enemies, and I'll be working on the getting score for other actions, since this is a really important feature, I'll take this part since no one starts it

**Comment by hongjiehuang** [comment]
I think Runmin has finished this part
