### ISSUE TITLE
Look into documentation

### ISSUE THREAD

**Issue by RyanLinrm** [RyanLinrm/CSC473Project#126]
https://docusaurus.io/  or jsdoc are the suggetstion source from professor

**Comment by nmaswood98** [comment]
I looked into docusarus and JSDoc. I believe that JSDoc would be better because of the auto generation based on the comments. We can also write the doc as we write new functions which would be very good as we expand the project.

**Comment by nmaswood98** [comment]
I installed JSDoc and began to document the the player class. Install js doc using "npm install jsdoc - g". And then use the command inside the folder "jsdoc -c jsdoc.json". 

To look at the documentation look inside the doc folder and open the index.html file.
