### ISSUE TITLE
need a main character sprite class

### ISSUE THREAD

**Issue by hongjiehuang** [RyanLinrm/CSC473Project#13]
We will need to build a character sprite class where we will set up the basic properties of a character including HP, ability, movement speed and so on.

**Comment by nmaswood98** [comment]
I created the main player class and moved the attack function into it under the function createWeapon. Later on we can create more players types extending from this class and modify the createWeapon class to customize it to each class

**Comment by nmaswood98** [comment]
Next we probably should move the movement and animation and create methods inside the player class so the main scene class is less messy and the code for movement is contained inside the player class.  We might want this to be a separate method?
