### ISSUE TITLE
Need to remove redundant ID's in multiple classes.

### ISSUE THREAD

**Issue by nmaswood98** [RyanLinrm/CSC473Project#135]
The classes playscene, playscenemultiplayer, player, unit and probably more have multiple ID types. uID, id, seatnumber, tower_id etc.

Many of this seams very redundant and would be useful to just combine them all and have a single id property for every object.

**Comment by RyanLinrm** [comment]
I've delete the towerID in the units class since its useless now, but I think other ID's still have some associated functions linked to them, we can begin to delete some of them while we doing the documentation

**Comment by hongjiehuang** [comment]
I THINK THE ISSUE IS NOT EXISTING ANYMORE
