### ISSUE TITLE
Character sprites/Game objects need a HP state

### ISSUE THREAD

**Issue by RyanLinrm** [RyanLinrm/CSC473Project#17]
In order to resolve the stage of game over which means our character is dead, or kill other game objects, we need HP state to represent that health of certain object, and this can be linked to the previous issue( detect attacked algorithm).

**Comment by nmaswood98** [comment]
I added a healthPoints attribute to the player class that will be used to keep track of health. I also renamed hp to healthPoints in Units I think its more descriptive.
