### ISSUE TITLE
Move all animations for entities into their respective classes. 

### ISSUE THREAD

**Issue by nmaswood98** [RyanLinrm/CSC473Project#58]
We need to move animations into their respective classes such that the animation is based on the movement and behavior. For example if the velocity of player is -64 the correct animation inside the player class itself will play. 

Moving all the animations out of  PlayScene into their respective classes allows us to be more flexible with multiplayer and single player since it will be using the same logic.

**Comment by hongjiehuang** [comment]
I have created a file containing the function that calls all the animations, and we can use them according to the player id or enemy id.
