### ISSUE TITLE
Wining and losing condition and handler

### ISSUE THREAD

**Issue by RyanLinrm** [RyanLinrm/CSC473Project#96]
We need to handler wining and losing in multiplayer scene

**Comment by nmaswood98** [comment]
I created a handler in the play scene TowerDestroyed runs when a players towers gets destroyed which means that they lose the game. In the multiplayer scene this stops and removes all the database handlers

**Comment by nmaswood98** [comment]
When 3 towers are destroyed the last player standing gets the game to end and "You win" appears. The handler is wonGame handler where we can put the other things that we need to do.
